[package]
name = "gdrive-linux"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.57"
ctrlc = "3.2.2"
hyper = { version = "0.14.19", features = ["server"] }
lazy_static = "1.4.0"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
tokio = { version = "1.19.2", features = ["full"] }
warp = { version = "0.3.2", default-features = false }
